package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// OmegaDomainSpec is the desired-state half of an OmegaDomain. Mirrors
// the storage.Domain shape that /v1/domains accepts on the wire - the
// reconciler is a thin "translate spec to HTTP POST" loop, intentionally
// so the CRD never drifts from the HTTP API.
type OmegaDomainSpec struct {
	// DomainName is the SPIFFE-style namespace identifier (e.g.
	// "media.news"). If empty, metadata.name is used.
	DomainName string `json:"domainName,omitempty"`
	// Description is a free-form operator-facing label.
	Description string `json:"description,omitempty"`
	// Admins are SPIFFE IDs that administer this domain and every
	// domain below it. Applied when the domain is created.
	Admins []string `json:"admins,omitempty"`
}

// OmegaDomainStatus reports the result of the most recent reconcile.
// The Ready condition reflects whether the domain currently exists on
// the Omega control plane; observedGeneration tracks which spec
// generation produced the status.
type OmegaDomainStatus struct {
	// ObservedGeneration is the .metadata.generation the status was
	// computed against.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
	// Conditions follow the standard Kubernetes condition convention.
	// The "Ready" condition is true after a successful POST /v1/domains
	// or after the domain is observed already-existing.
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=odom

// OmegaDomain is a Kubernetes-managed Omega domain. Cluster-scoped
// because Omega's domain hierarchy (media, media.news) is global, not
// tied to a Kubernetes namespace. A domain's parent must exist first.
type OmegaDomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              OmegaDomainSpec   `json:"spec,omitempty"`
	Status            OmegaDomainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OmegaDomainList is the response shape kubectl uses for `kubectl get omegadomain`.
type OmegaDomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OmegaDomain `json:"items"`
}

func init() {
	register(&OmegaDomain{}, &OmegaDomainList{})
}

// DeepCopyInto / DeepCopy / DeepCopyObject are normally generated by
// controller-gen. We hand-write them here to avoid pulling code
// generation into the build; they are tiny because the spec is two
// strings and a slice and the status is two slices.

func (in *OmegaDomain) DeepCopyInto(out *OmegaDomain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	if in.Spec.Admins != nil {
		out.Spec.Admins = append([]string(nil), in.Spec.Admins...)
	}
	in.Status.DeepCopyInto(&out.Status)
}

func (in *OmegaDomain) DeepCopy() *OmegaDomain {
	if in == nil {
		return nil
	}
	out := new(OmegaDomain)
	in.DeepCopyInto(out)
	return out
}

func (in *OmegaDomain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OmegaDomainList) DeepCopyInto(out *OmegaDomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]OmegaDomain, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *OmegaDomainList) DeepCopy() *OmegaDomainList {
	if in == nil {
		return nil
	}
	out := new(OmegaDomainList)
	in.DeepCopyInto(out)
	return out
}

func (in *OmegaDomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OmegaDomainStatus) DeepCopyInto(out *OmegaDomainStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}
